### ISSUE TITLE
Fedora Linux: Flatpak version isn't importing or listing installed addons, AppImage spins endlessly

### ISSUE THREAD

**Issue by msmafra** [arviceblot/eso-addons#169]
Hello there!

I installed first via Flatpak, gave permissions to the addons and Minion folders, but it never shows my addons nor it imports from Minion, which I'm not sure to what file to point to ($HOME/.minion/minion.xml?).
Trying the AppImage, it opens to a spinning state and never ends.
I'm on Fedora 39, both minion manual and from Flatpak works with the same folders. Any other permissions to give?
[flatpak version]
![Captura de tela de 2024-01-30 11-12-57](https://github.com/arviceblot/eso-addons/assets/1005457/6c0ccdbf-36dd-40d6-9d9b-df782d045a0d)
[AppImage]
![Captura de tela de 2024-01-30 11-22-16](https://github.com/arviceblot/eso-addons/assets/1005457/3deaf927-7365-48e8-a9fa-9053db7c87e4)

**Comment by msmafra** [comment]
Both AppImage and the "unknown Linux gnu" version show this when ran from a terminal:
```
 ./eso-addon-manager-x86_64-unknown-linux-gnu
2024-01-30T14:28:28.917351Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConfigParse { source: Error("EOF while parsing a value", line: 1, column: 0), path: "/home/marcelo/.config/eso-addons/config.json" }', core/src/config.rs:86:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:102:37
2024-01-30T14:28:34.405397Z  WARN egui_glow::painter: You forgot to call destroy() on the egui glow painter. Resources will leak!
```

And both keep spinning endlessly.

**Comment by msmafra** [comment]
```
❯ cargo run
warning: unused import: `Path`
 --> core/src/service/mod.rs:4:17
  |
4 | use std::path::{Path, PathBuf};
  |                 ^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `update`
   --> core/src/service/mod.rs:185:13
    |
185 |         for update in updates.iter() {
    |             ^^^^^^ help: if this is intentional, prefix it with an underscore: `_update`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: method `get_missing_addon_detail_ids` is never used
   --> core/src/service/mod.rs:291:14
    |
47  | impl AddonService {
    | ----------------- method in this implementation
...
291 |     async fn get_missing_addon_detail_ids(&self) -> Result<Vec<i32>> {
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: function `fs_get_addon` is never used
  --> core/src/service/fs_util.rs:22:8
   |
22 | pub fn fs_get_addon(addon_dir: &PathBuf, name: &str) -> Result<Option<...
   |        ^^^^^^^^^^^^

warning: function `fs_get_addons` is never used
  --> core/src/service/fs_util.rs:28:8
   |
28 | pub fn fs_get_addons(addon_dir: &PathBuf) -> Result<AddonList> {
   |        ^^^^^^^^^^^^^

warning: `eso-addons-core` (lib) generated 5 warnings (run `cargo fix --lib -p eso-addons-core` to apply 2 suggestions)
warning: unused import: `VecDeque`
 --> src/views/installed.rs:1:33
  |
1 | use std::collections::{HashMap, VecDeque};
  |                                 ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `ctx`
   --> src/views/addon_details.rs:109:9
    |
109 |         ctx: &egui::Context,
    |         ^^^ help: if this is intentional, prefix it with an underscore: `_ctx`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `addon_id`
  --> src/views/browse.rs:41:29
   |
41 |     fn install_addon(&self, addon_id: i32, service: &mut AddonService) {
   |                             ^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_addon_id`

warning: unused variable: `service`
  --> src/views/browse.rs:41:44
   |
41 |     fn install_addon(&self, addon_id: i32, service: &mut AddonService) {
   |                                            ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_service`

warning: unused variable: `ctx`
  --> src/views/browse.rs:49:9
   |
49 |         ctx: &eframe::egui::Context,
   |         ^^^ help: if this is intentional, prefix it with an underscore: `_ctx`

warning: unused variable: `service`
  --> src/views/missing_deps.rs:36:24
   |
36 |     fn poll(&mut self, service: &mut AddonService) {
   |                        ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_service`

warning: unused variable: `ctx`
   --> src/views/missing_deps.rs:100:9
    |
100 |         ctx: &eframe::egui::Context,
    |         ^^^ help: if this is intentional, prefix it with an underscore: `_ctx`

warning: unused variable: `i`
   --> src/views/ui_helpers.rs:288:53
    |
288 | ...egui::Ui, node: &BBNode, i: i32, parent_nodes: &[BBNode]) {
    |                             ^ help: if this is intentional, prefix it with an underscore: `_i`

warning: associated function `new` is never used
  --> src/views/ui_helpers.rs:61:12
   |
60 | impl<T: Send + Clone + Default> PromisedValue<T> {
   | ------------------------------------------------ associated function in this implementation
61 |     pub fn new(value_promise: ImmediateValuePromise<T>) -> Self {
   |            ^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `eso-addon-manager` (bin "eso-addon-manager") generated 9 warnings (run `cargo fix --bin "eso-addon-manager"` to apply 8 suggestions)
    Finished dev [unoptimized + debuginfo] target(s) in 1.05s
     Running `target/debug/eso-addon-manager`
2024-01-30T14:44:12.043592Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1
2024-01-30T14:44:12.346344Z  INFO eso_addons_core::config: Loading config data at: /home/marcelo/.config/eso-addons/config.json
2024-01-30T14:44:12.347133Z  INFO eso_addons_core::api: Requesting: https://api.mmoui.com/v3/globalconfig.json
2024-01-30T14:44:12.578263Z  INFO eso_addons_core::api: Requesting: https://api.mmoui.com/v3/game/ESO/gameconfig.json
2024-01-30T14:44:12.756311Z  INFO sea_orm_migration::migrator: Applying all pending migrations
2024-01-30T14:44:12.757508Z  INFO sea_orm_migration::migrator: No pending migrations
2024-01-30T14:44:12.779134Z  INFO eso_addon_manager::views::installed: Checking for updates
2024-01-30T14:44:12.779270Z  INFO eso_addons_core::service: Updating categories
2024-01-30T14:44:12.779296Z  INFO eso_addons_core::api: Requesting: https://api.mmoui.com/v3/game/ESO/categorylist.json
2024-01-30T14:44:12.957845Z  INFO eso_addons_core::api: Requesting: https://api.mmoui.com/v3/game/ESO/filelist.json
2024-01-30T14:44:13.774524Z  INFO eso_addons_core::service: Checking for missing dependencies
2024-01-30T14:44:13.775339Z  INFO eso_addons_core::service: Saving config
2024-01-30T14:44:13.779716Z  INFO eso_addon_manager::views::installed: Getting installed addons
2024-01-30T14:44:13.779848Z  INFO eso_addons_core::service: Getting installed addons
2024-01-30T14:44:13.781729Z  INFO eso_addons_core::service: Done getting addons!
2024-01-30T14:44:13.792863Z  INFO eso_addon_manager::views::installed: Sorting addons
thread 'tokio-runtime-worker' panicked at core/src/service/mod.rs:742:43:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-01-30T14:45:36.663051Z  INFO eso_addon_manager::views::installed: Getting installed addons
2024-01-30T14:45:36.663201Z  INFO eso_addons_core::service: Getting installed addons
2024-01-30T14:45:36.664790Z  INFO eso_addons_core::service: Done getting addons!
2024-01-30T14:45:36.676529Z  INFO eso_addon_manager::views::installed: Sorting addons
2024-01-30T14:45:41.757197Z  INFO eso_addon_manager::views::installed: Getting installed addons
2024-01-30T14:45:41.757321Z  INFO eso_addons_core::service: Getting installed addons
2024-01-30T14:45:41.759178Z  INFO eso_addons_core::service: Done getting addons!
2024-01-30T14:45:41.771230Z  INFO eso_addon_manager::views::installed: Sorting addons
```

**Comment by arviceblot** [comment]
Hmm, unfortunately I have done a poor job documenting the Minion import process. I wasn't sure how much demand there would be for this feature before releasing to flathub.

It is designed to load the `BU-addons.txt` file. I'm not sure where this file is located but it's possible it is generated in backup functionality of minion. It should be a plaintext file with comma-separated numbers (`7,56,288,[... etc]`).

If you can find that file, I would recommend trying to import it again. It should work regardless of the install method and shouldn't need additional filesystem permissions, as it requests host access.


I will work on better documenting that process in the app. I would really appreciate if you could pass on what you do to load it if you get it working (where the txt file is stored, generated, anything really), this would greatly help me in documenting the instructions.

###### *Also, thank you for the interest in this project!*

**Comment by arviceblot** [comment]
> Both AppImage and the "unknown Linux gnu" version show this when ran from a terminal:
> 
> ```
>  ./eso-addon-manager-x86_64-unknown-linux-gnu
> 2024-01-30T14:28:28.917351Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1
> thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConfigParse { source: Error("EOF while parsing a value", line: 1, column: 0), path: "/home/marcelo/.config/eso-addons/config.json" }', core/src/config.rs:86:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:102:37
> 2024-01-30T14:28:34.405397Z  WARN egui_glow::painter: You forgot to call destroy() on the egui glow painter. Resources will leak!
> ```
> 
> And both keep spinning endlessly.

Sorry about this, the appimage and linux binary in the releases page are out of date and may not work on new installs.

**Comment by msmafra** [comment]
> Hmm, unfortunately I have done a poor job documenting the Minion import process. I wasn't sure how much demand there would be for this feature before releasing to flathub.
> 
> It is designed to load the `BU-addons.txt` file. I'm not sure where this file is located but it's possible it is generated in backup functionality of minion. It should be a plaintext file with comma-separated numbers (`7,56,288,[... etc]`).
> 
> If you can find that file, I would recommend trying to import it again. It should work regardless of the install method and shouldn't need additional filesystem permissions, as it requests host access.
> 
> I will work on better documenting that process in the app. I would really appreciate if you could pass on what you do to load it if you get it working (where the txt file is stored, generated, anything really), this would greatly help me in documenting the instructions.
> 
> ###### _Also, thank you for the interest in this project!_

I'll try, but even cloning and running the project locally I couldn't make it work pointing to the correct folder with the needed permissions. I'll try importing the CSV file, it's probably inside $HOME/.minion. I'm not sure about Minion's flatpak version if it's inside $HOME/.var/app/gg.minion.Minion or if it uses the same one.
I was already for a long time concerned with Minion not updating in so long. And ESO-Addons having Windows and Mac binaries, is easier to recommend to the ESO community.

**Comment by msmafra** [comment]
A file with the name BU-addons.txt does exist on my system, I did not find it at least for both the flatpak and the java version of Minion (both pointing to the same $HOME/.minion folder. Flatpak backups I have no idea where they are stored. Couldn't find them despite they being listed inside Minion. 
The backup option creates a .zip file containing a "mirror" of the path for the ESO addons folder with all sub-folders, like: mnt/Games/SteamLibrary/steamapps/compadata/306130/pfx/drive_c/users/steamuser/Documents/Elder Scrolls Online/live.AddOns. And also creates a text file containing, what I guess being the addons codes separated by commas.

Importing the .txt file listed all my addons, but the importing process never ends spinning and showing Importing... in the button. Looking at the process, it makes me thing that setting the Addons folder path is buggy since it nothing will happen until a .txt file is imported.

I think some changes, graphically at least, to make it easier, simpler and friendlier would be nice like.

- Bigger tab/buttons;
- Bigger font;
- First run screen for helping importing/configuring;
- More contrast on the lines/table to distinguish where one addon begins and other ends;
- a filter inside the Browse tab;
- remove the host access on the flatpak version; For flatpak it should have as minimum access to the system as possible;

It also doesn't occupy the whole window

![Captura de tela de 2024-01-31 00-09-34](https://github.com/arviceblot/eso-addons/assets/1005457/b7009842-c2f9-481a-bf32-3ce8ecda55d1)

After configuring and importing, if I close it opens like this:
![Captura de tela de 2024-01-31 00-30-39](https://github.com/arviceblot/eso-addons/assets/1005457/df698f16-eaf7-4eb5-8fee-e567c222a8da)

all dependencies are fulfilled already, since those are, at least should be, the addons I'm using.

**Comment by arviceblot** [comment]
All of those are great points and some are in progress (onboarding, filtering). The dependency page needs cleanup and more explanation.

I agree on the host access, but it would go against my main use case which is to make easy to install and use on the Steam Deck. To manage directory access would mean switching to desktop mode and probably connecting a keyboard to enter the commands. The primary goal is to:

1. Install from flathub
2. Select game install dir
3. Start installing addons

But I realize that is conflicting to it's use as a general production-ready desktop app, rather than a hobby project.

I am open to PRs if someone wants to take a stab at improving the look and theme, as it is using the default egui theme. It's on my todo, but quite further down.

**Comment by arviceblot** [comment]
v0.4.8 is out on flathub now with a bunch of layout changes. Minion import should work better now.

I'm not sure if the design is any _better_, but most of the button sizes and headings are larger.

Also removed host fs permission, so you might want to check your addon path before changing addons.

**Comment by msmafra** [comment]
> v0.4.8 is out on flathub now with a bunch of layout changes. Minion import should work better now.
> 
> I'm not sure if the design is any _better_, but most of the button sizes and headings are larger.
> 
> Also removed host fs permission, so you might want to check your addon path before changing addons.

Very good. Much more legible.
Unfortunetly maximizing the windows is not adapting the table width;
The Importing process still not clear and if I confirm by clicking open, clicking the refresh button or pressing Enter, in any stage without even choosing a file, it will show as Importing without the option to cancel;
I'd like to recomment a dialog to confirm after clicking the Quit option.
